language: node_js

cache:
    - npm
    - yarn

node_js:
    - "lts/*"
    - "node"

after_success:
    - if [ -n "$TRAVIS_TAG" ]; then npm version $TRAVIS_TAG; fi
    - yarn build

deploy:
    - provider: npm
      email: richiebendall@gmail.com
      skip_cleanup: true
      api_key: $npm_token
      on:
          tags: true
